# Write your MySQL query statement below
SELECT TRANSACTION_ID
FROM TRANSACTIONS 
WHERE (DATE(DAY), AMOUNT) IN 
(
        SELECT DATE(DAY), MAX(AMOUNT) AS AMT 
        FROM TRANSACTIONS
        GROUP BY DATE(DAY)
)
ORDER BY TRANSACTION_ID
